#
# Paleobiology Database - Macrostrat API image
# 
# This file is used to build the preload image for the Paleomacro project MariaDB
# container. This image is used both by Macrostrat and by the Paleobiology Database.
# It contains a number of useful packages. The Dockerfile found in the same directory
# then uses the preload image as a base to build the mariadb container image
# very quickly by copying in the database configuration files. You can build this
# preload image locally using the command 'pbdb build preload mariadb'.

FROM keymetrics/pm2:latest-stretch as paleomacro_msapi_preload

RUN apt-get update && \
    apt-get -y install libterm-readline-gnu-perl && \
    apt-get -y install apt-utils && \
    apt-get -y install vim && \
    apt-get -y install redis-tools && \
    apt-get -y install postgresql-client && \
    apt-get -y install locales && \
    apt-get -y install tzdata && \
    locale-gen --purge en_US.UTF-8 && \
